# Generated by Django 3.2.7 on 2021-10-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
